## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

import ns3waf

def configure(conf):
    ns3waf.check_modules(conf, ['core', 'network', 'dce', 'point-to-point'], mandatory = True)

def build(bld):
    bld.build_a_script('dce', needed = ['core', 'network', 'dce', 'point-to-point', 'csma'],
				  target='bin/my-sctp-test',
				  source=['myscripts-sctp-sim.cc'],)
				  
    bld.program(source='my-sctp-server.cc', target='../../bin_dce/my-sctp-server',
                cxxflags = [ '-fPIC'], 
                linkflags = ['-lsctp', '-lstdc++', '-pie', '-rdynamic'])

    bld.program(source='my-sctp-client.cc', target='../../bin_dce/my-sctp-client',
                cxxflags = [ '-fPIC'], 
                linkflags = ['-lsctp', '-lstdc++', '-pie', '-rdynamic'])
